#
#   Copyright 2011 Ricky Chilcott <chilcotr@ohio.edu>
#   with help from Geordie Korper <geordie@korper.org>
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#       You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
# 
#  Luggage makefile for building a package that copies postflight script to /usr/local/munki.

include /usr/local/share/luggage/luggage.make
include ../luggage_munki_helper.make

TITLE=Munki_OU_Preflight
REVERSE_DOMAIN=edu.ohio.oit.pkg
PAYLOAD=pack-usr-local-munki-preflight
PACKAGE_VERSION=1.1
