#!/bin/sh

TARGET_PATH=$2
MANAGED_INSTALL_DIR="$TARGET_PATH/Library/Managed Installs"
MSU_PREFS="$TARGET_PATH/Library/Preferences/ManagedInstalls"

# Load default munki LaunchDaemon, because we used to disable this one
/bin/launchctl load -w /Library/LaunchDaemons/com.googlecode.munki.managedsoftwareupdate-check.plist

# Unload and then remove our (now deprecated) LaunchDaemon
/bin/launchctl unload -w /Library/LaunchDaemons/edu.ohio.munki.managedsoftwareupdate-check.plist
/bin/rm /Library/LaunchDaemons/edu.ohio.munki.managedsoftwareupdate-check.plist

#Make Munki directories more secure
mkdir -p "$MANAGED_INSTALL_DIR"
/usr/sbin/chown -R root:wheel "$MANAGED_INSTALL_DIR"
/bin/chmod -R 755 "$MANAGED_INSTALL_DIR"

mkdir -p "$MANAGED_INSTALL_DIR/catalogs"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/catalogs"

mkdir -p "$MANAGED_INSTALL_DIR/Archives"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/Archives"

mkdir -p "$MANAGED_INSTALL_DIR/Logs"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/Logs"

mkdir -p "$MANAGED_INSTALL_DIR/manifests"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/manifests"

mkdir -p "$MANAGED_INSTALL_DIR/certs"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/certs"

mkdir -p "$MANAGED_INSTALL_DIR/client_resources"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/client_resources"

mkdir -p "$MANAGED_INSTALL_DIR/Cache"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/Cache"

mkdir -p "$MANAGED_INSTALL_DIR/swupd"
/bin/chmod 700 "$MANAGED_INSTALL_DIR/swupd"

#Set MunkiServer Locations
/usr/bin/defaults write $MSU_PREFS SoftwareRepoURL 		"https://munki.test.oit.ohio.edu"
/usr/bin/defaults write $MSU_PREFS ManifestURL 			  "https://munki.test.oit.ohio.edu"

#Set Core Preferences, only include items which need to be modified from default
/usr/bin/defaults write $MSU_PREFS SuppressStopButtonOnInstall -bool true
/usr/bin/defaults write $MSU_PREFS InstallAppleSoftwareUpdates -bool true
/usr/bin/defaults write $MSU_PREFS FollowHTTPRedirects         -string "https"

# Check for updates after restart
mkdir -p $TARGET_PATH/Users/Shared
/usr/bin/touch $TARGET_PATH/Users/Shared/.com.googlecode.munki.checkandinstallatstartup
