#!/bin/sh

TARGET_PATH=$2
MSU_PREFS="$TARGET_PATH/Library/Preferences/ManagedInstalls"

#Set Lab Preferences
/usr/bin/defaults write $MSU_PREFS AppleSoftwareUpdatesOnly      -bool false
/usr/bin/defaults write $MSU_PREFS InstallAppleSoftwareUpdates   -bool true
/usr/bin/defaults write $MSU_PREFS SuppressUserNotification      -bool true
/usr/bin/defaults write $MSU_PREFS SuppressStopButtonOnInstall   -bool true
/usr/bin/defaults write $MSU_PREFS ShowRemovalDetail             -bool false
/usr/bin/defaults write $MSU_PREFS DaysBetweenNotifications		 1

# Blockup Update settings
/usr/bin/defaults write $MSU_PREFS BlockUpdateStartTime 	-string "8:00"
/usr/bin/defaults write $MSU_PREFS BlockUpdateEndTime   	-string "18:00"
/usr/bin/defaults write $MSU_PREFS BlockUpdateDays      	-string "0,1,2,3,4"