#!/bin/sh

#Set MunkiServer Preferences
defaults write /Library/Preferences/ManagedInstalls SoftwareRepoURL "https://munki.test.oit.ohio.edu"
defaults write /Library/Preferences/ManagedInstalls ManifestURL "https://munki.test.oit.ohio.edu"

#Set Lab Preferences
defaults write /Library/Preferences/ManagedInstalls AppleSoftwareUpdatesOnly -bool false
defaults write /Library/Preferences/ManagedInstalls InstallAppleSoftwareUpdates -bool false
defaults write /Library/Preferences/ManagedInstalls SuppressUserNotification -bool true
defaults write /Library/Preferences/ManagedInstalls SuppressStopButtonOnInstall -bool true
defaults write /Library/Preferences/ManagedInstalls ShowRemovalDetail -bool false